# Generated by Django 4.1.5 on 2023-01-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'pending'), ('D', 'done'), ('NS', 'not started')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('status', models.BooleanField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paging.process')),
            ],
        ),
    ]
