# Generated by Django 4.1.5 on 2023-01-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='consumed_memory',
            field=models.IntegerField(null=True),
        ),
    ]
