# Generated by Django 4.1.5 on 2023-01-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0002_memory_consumed_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='consumed_memory',
            new_name='left_memory',
        ),
    ]
