# Generated by Django 4.1.5 on 2023-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0003_alter_memory_page_count_alter_memory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='left_page',
            field=models.IntegerField(null=True),
        ),
    ]
