# Generated by Django 4.1.5 on 2023-01-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0003_rename_consumed_memory_memory_left_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.IntegerField(unique=True),
        ),
    ]
