# Generated by Django 4.1.5 on 2023-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0004_alter_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.CharField(default='paging', max_length=10),
            preserve_default=False,
        ),
    ]
