# Generated by Django 4.1.5 on 2023-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0004_memory_left_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='page_size',
            field=models.IntegerField(null=True),
        ),
    ]
