# Generated by Django 4.1.5 on 2023-01-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0005_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='init_duration',
            field=models.IntegerField(null=True),
        ),
    ]
