# Generated by Django 4.1.5 on 2023-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0005_memory_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='required_memory',
            field=models.IntegerField(null=True),
        ),
    ]
