# Generated by Django 4.1.5 on 2023-01-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0006_process_required_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='required_memory',
        ),
    ]
