# Generated by Django 4.1.5 on 2023-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0006_process_init_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('IP', 'in process'), ('D', 'done')], default='NS', max_length=3),
        ),
    ]
