# Generated by Django 4.1.5 on 2023-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0007_alter_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='page_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('IP', 'in process'), ('D', 'done')], default='P', max_length=3),
        ),
    ]
