# Generated by Django 4.1.5 on 2023-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paging', '0008_process_page_used_alter_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('IP', 'in process'), ('D', 'done'), ('T', 'terminated')], default='P', max_length=3),
        ),
    ]
